const axios = require('axios');
const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
require('dotenv').config();

const API_URL = 'http://localhost:5000/api';
const MONGO_URI = "mongodb+srv://discord:TH3R890ie9VzACpX@cluster0.whxj5zj.mongodb.net/codegenesis?retryWrites=true&w=majority&appName=Cluster0";
const JWT_SECRET = process.env.JWT_SECRET || "b1c3a42a9367c4b83fe7633960c483a260c267a7bb2a3654541c0e2802c66d31";

// Users to test
// Users to test
// Using known emails from previous debugging. 
// Note: yassine1 vs yassinel was a potential confusion.
// Based on actual DB find success in link-parent-child.js, we will try fuzzy finding if strict fails.
const PARENT_EMAIL_TYPED = 'yassine1.gmatii@gmail.com';
const PARENT_EMAIL_DETECTED = 'yassinel.gmatii@gmail.com';
const CHILD_EMAIL = 'genesiscodee@gmail.com';


const generateToken = (user) => {
    return jwt.sign(
        { id: user._id, email: user.email, userType: user.userType, firebaseUid: user.firebaseUid },
        JWT_SECRET,
        { expiresIn: '1h' }
    );
};

const runTests = async () => {
    try {
        console.log('🔄 Connecting to DB to fetch users...');
        await mongoose.connect(MONGO_URI);
        const User = require('./src/models/User'); // Adjust path relative to script location

        // Check flexible parent search to handle typo 'yassine1' vs 'yassinel'
        let parent = await User.findOne({ email: PARENT_EMAIL_TYPED });
        if (!parent) {
            console.log(`⚠️  Parent not found via ${PARENT_EMAIL_TYPED}, trying ${PARENT_EMAIL_DETECTED} and fuzzy search...`);
            parent = await User.findOne({ email: PARENT_EMAIL_DETECTED });

            if (!parent) {
                // Fuzzy search
                const pList = await User.find({ userType: 'parent' }).limit(1);
                if (pList.length > 0) parent = pList[0];
            }
        }
        const child = await User.findOne({ email: CHILD_EMAIL });

        if (!parent || !child) {
            console.error('❌ Could not find parent or child in DB.');
            console.log('Parent:', parent ? 'Found' : 'Missing');
            console.log('Child:', child ? 'Found' : 'Missing');
            process.exit(1);
        }

        console.log('✅ Users found.');
        const parentToken = generateToken(parent);
        const childToken = generateToken(child);

        // We don't need DB connection anymore for API tests, but keep it if we need direct verification
        // await mongoose.disconnect(); 

        // ==========================================
        // TEST 1: PROFILE (User Controller)
        // ==========================================
        console.log('\n🔍 TEST 1: Profile Endpoint');
        try {
            const res = await axios.get(`${API_URL}/users/profile`, {
                headers: { Authorization: `Bearer ${parentToken}` }
            });
            console.log(`   ✅ Parent Profile fetched: ${res.data.user.email}`);
        } catch (e) {
            console.error('   ❌ Parent Profile Failed:', e.message);
        }

        try {
            const res = await axios.get(`${API_URL}/users/profile`, {
                headers: { Authorization: `Bearer ${childToken}` }
            });
            console.log(`   ✅ Child Profile fetched: ${res.data.user.email}`);
        } catch (e) {
            console.error('   ❌ Child Profile Failed:', e.message);
        }

        // ==========================================
        // TEST 2: CREATE TASK (Parent -> Child)
        // ==========================================
        console.log('\n🔍 TEST 2: Task Creation');
        let taskId;
        try {
            // NOTE: The endpoint verified in previous turns for task assignment involved 'assigned-tasks',
            // but the user only has 'tacheDeJour' open which might use 'tasks' endpoint?
            // Let's try the generic /api/tasks first as seen in taskController.
            // But taskController createTask requires `userId` in body.

            const taskPayload = {
                userId: child._id.toString(),
                title: 'Backend Test Task',
                description: 'Generated by verification script',
                type: 'daily',
                xpReward: 100
            };

            const res = await axios.post(`${API_URL}/tasks`, taskPayload, {
                headers: { Authorization: `Bearer ${parentToken}` }
            });
            taskId = res.data._id;
            console.log(`   ✅ Task Created ID: ${taskId} for Child`);
        } catch (e) {
            console.error('   ❌ Task Creation Failed:', e.response?.data || e.message);
        }

        // ==========================================
        // TEST 3: GET TASKS (Child View)
        // ==========================================
        console.log('\n🔍 TEST 3: Fetch Tasks (Child)');
        if (taskId) {
            try {
                // Determine correct endpoint. taskController getTasks uses /api/tasks?userId=...
                // Ideally child calls /api/tasks?userId=MyID
                const res = await axios.get(`${API_URL}/tasks?userId=${child._id}&type=daily`, {
                    headers: { Authorization: `Bearer ${childToken}` }
                });
                const tasks = res.data;
                const found = tasks.find(t => t._id === taskId);
                console.log(`   ✅ Child Task List Fetched: ${tasks.length} items`);
                if (found) {
                    console.log(`   ✅ Newly created task found in list.`);
                } else {
                    console.error(`   ❌ Newly created task NOT found in list.`);
                }
            } catch (e) {
                console.error('   ❌ Fetch Tasks Failed:', e.message);
            }
        }

        // ==========================================
        // TEST 4: COMPLETE TASK (Child updates status)
        // ==========================================
        console.log('\n🔍 TEST 4: Complete Task');
        if (taskId) {
            try {
                const res = await axios.put(`${API_URL}/tasks/${taskId}`, {
                    status: 'completed'
                }, {
                    headers: { Authorization: `Bearer ${childToken}` }
                });

                if (res.data.status === 'completed') {
                    console.log(`   ✅ Task marked as completed.`);
                } else {
                    console.error(`   ❌ Task update returned status: ${res.data.status}`);
                }
            } catch (e) {
                console.error('   ❌ Complete Task Failed:', e.response?.data || e.message);
            }
        }

        // ==========================================
        // TEST 5: CATEGORY ACCESS (Mock Check)
        // ==========================================
        console.log('\n🔍 TEST 5: Category Access');
        // This usually requires a valid category ID. Let's list categories first if possible.
        // Assuming we have a categoryController.
        // OR we can just check the CategoryAccess model directly since we are connected to DB.
        const CategoryAccess = require('./src/models/CategoryAccess');
        const count = await CategoryAccess.countDocuments({ user: child._id });
        console.log(`   ℹ️ Child has ${count} CategoryAccess entries.`);

        if (count > 0) {
            const first = await CategoryAccess.findOne({ user: child._id });
            console.log(`   Sample Access: Category ${first.category} - Status: ${first.status}`);
        } else {
            console.log('   ℹ️ No CategoryAccess found for child. Skipping deep access test.');
        }

        console.log('\n✅ Verification Script Completed.');

    } catch (error) {
        console.error('\n🚨 Global Script Error:', error);
    } finally {
        await mongoose.disconnect();
    }
};

runTests();
